### ISSUE TITLE
feed the duck

### ISSUE THREAD

**Issue by Bergiu** [BergiuTelegram/TgEntenBot#6]
add the possibility to feed the duck with a sticker or emoji so it's quiet for a few minutes

**Comment by JosXa** [comment]
Make "Duckfood" stickerpack with 
http://www.futtermittel-chemnitz.de/wp-content/uploads/2017/07/GE-Futter-Sack-1-1000-208x300.jpg
http://img.fotocommunity.com/entenfutter-d3c14bb7-f2ae-480f-b0d6-d538a4e4f4ea.jpg?height=1080
http://themetapicture.com/media/funny-duck-food-hungry-hand.jpg
and
https://www.ndtv.com/cooks/images/kasha-bread.jpg
